### PR TITLE
update setup instructions to have nglview install

### PR DESCRIPTION
**Pull request by janash**

### CODE REVIEW

**Comment by hainm** [comment]
hi the version for nglview is very outdated. Should be 3.0.3 (not v0.6.x.x)
https://anaconda.org/conda-forge/nglview

**Comment by janash** [comment]
HI @hainm - this is an oversight on my part. I updated these instructions from using py3dmol from another lesson and instead of creating a new figure, I typed "nglview" over "py3dmol" in photoshop. When someone uses Anaconda Navigator, they should get an updated version that is on conda-forge. We are not telling them to install this version of nglview, just to search for it using the feature in anaconda navigator and installs what comes up. I will fix the figure when I get the chance.

**Comment by janash** [comment]
@hainm - do you have a recommendation for getting anaconda navigator to give the correct version? command line install is an option, but we're trying to avoid that. I have done nothing to specify version, this is what comes up in Anaconda's graphical interface when nglview is searched

**Comment by janash** [comment]
I think perhaps if they use "update index" as instructed it will get the correct version. I was making the figure quickly this morning and will update the version number and instructions to check for it soon. I typically use command line and not the Anaconda navigator to install packages, and I actually installed it just for this figure :)

**Comment by hainm** [comment]
> @hainm - do you have a recommendation for getting anaconda navigator to give the correct version? command line install is an option, but we're trying to avoid that. I have done nothing to specify version, this is what comes up in Anaconda's graphical interface when nglview is searched

no I don't know. I have never used it.

**Pull request merged**
